[book]
authors = ["Mahmoud Harmouch"]
language = "en"
src = "src"
title = "AutoGPT: Pure Rust AI Agentic Framework."
description = "Official documentation for AutoGPT, a pure Rust framework for building blazingly fast, multimodal, zero-shot AI agents."

[output.html]
additional-css = ["theme/main.css", "theme/custom.css"]
additional-js = ["theme/custom.js", "mermaid/mermaid.min.js", "mermaid/mermaid-init.js"]
edit-url-template = "https://github.com/wiseaidotdev/autogpt/edit/main/docs/{path}"
git-repository-url = "https://github.com/wiseaidotdev/autogpt"
site-url = "https://autogpt.wiseai.dev/"
cname = "autogpt.wiseai.dev"
default-theme = "navy"
preferred-dark-theme = "navy"
smart-punctuation = true
no-section-label = false

[output.html.fold]
enable = true
level = 1

[output.html.playground]
editable = true
line-numbers = true
runnable = false

[output.html.search]
limit-results = 20
use-boolean-and = true
boost-title = 3
boost-hierarchy = 2
boost-paragraph = 1
expand = true
heading-split-level = 2

[preprocessor.links]

[preprocessor.mermaid]
command = "mdbook-mermaid"

